CREATE TABLE user_address (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	city VARCHAR(255) NOT NULL,
	state VARCHAR(255) NOT NULL,
	zip_code VARCHAR(20) NOT NULL,
	country VARCHAR(255) NOT NULL,
	contact_number VARCHAR(20) NOT NULL,
	is_default BOOLEAN,
	created_by VARCHAR(255),
	created_date TIMESTAMP DEFAULT NOW(),
	last_modified_by VARCHAR(255),
	last_modified_date TIMESTAMP DEFAULT NOW(),

	user_account_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX one_default_address_per_user
	    ON user_address(user_account_id) WHERE is_default = TRUE;