CREATE TABLE products (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	image_url VARCHAR(255) NOT NULL,
	description TEXT,
	price DECIMAL(10,2) NOT NULL,
	stock INT NOT NULL,
	created_by VARCHAR(255),
	created_date TIMESTAMP DEFAULT NOW(),
	last_modified_by VARCHAR(255),
	last_modified_date TIMESTAMP DEFAULT NOW()
);

CREATE TABLE cart (
	user_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	quantity INT NOT NULL,
	created_by VARCHAR(255),
	created_date TIMESTAMP DEFAULT NOW(),
	last_modified_by VARCHAR(255),
	last_modified_date TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (user_id, product_id),

	CONSTRAINT fk_cart_user
		FOREIGN KEY (user_id) REFERENCES user_account(id) ON DELETE CASCADE,

	CONSTRAINT fk_cart_product
		FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);