CREATE TABLE orders (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id BIGINT NOT NULL,
	shipping_address_id BIGINT NOT NULL,
	total_amount DECIMAL(10,2),
	status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
	created_by VARCHAR(255),
	created_date TIMESTAMP DEFAULT NOW(),
	last_modified_by VARCHAR(255),
	last_modified_date TIMESTAMP DEFAULT NOW(),

	CONSTRAINT fk_order_user_address
		FOREIGN KEY (shipping_address_id) REFERENCES user_address(id) ON DELETE CASCADE,

	CONSTRAINT fk_order_user
		FOREIGN KEY (user_id) REFERENCES user_account(id) ON DELETE CASCADE
);

CREATE TABLE order_item (
	order_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	product_name VARCHAR(255) NOT NULL,
	product_snapshot_price DECIMAL(10,2) NOT NULL,
	quantity INT NOT NULL,
	price DECIMAL(10,2) NOT NULL,
	created_by VARCHAR(255),
	created_date TIMESTAMP DEFAULT NOW(),
	last_modified_by VARCHAR(255),
	last_modified_date TIMESTAMP DEFAULT NOW(),

	PRIMARY KEY (order_id, product_id),

	CONSTRAINT fk_order_item_order
		FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,

	CONSTRAINT fk_order_item_product
		FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);